# Generated by Django 4.2.11 on 2024-05-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('bottleId', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_times_Sold', models.IntegerField(default=0)),
                ('bottle_status', models.CharField(choices=[('A', 'Available'), ('S', 'Sold'), ('D', 'Discarded')], default='A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BottleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfReturning', models.DateField(null=True)),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bottle')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_quantity', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Delivered'), ('C', 'Cancelled')], default='P', max_length=100)),
                ('order_notes', models.TextField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='myapp.address')),
                ('bottles', models.ManyToManyField(through='inventory.BottleOrder', to='inventory.bottle')),
                ('customer', models.ForeignKey(limit_choices_to={'type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(limit_choices_to={'type__in': ['admin', 'driver', 'customerService']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bottleorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orders'),
        ),
    ]
