# Generated by Django 4.2.11 on 2024-05-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_customer_orders_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='receiver_id',
            new_name='receiver',
        ),
    ]
