# Generated by Django 4.2.11 on 2024-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_bottle_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
